# Generated by Django 2.1.5 on 2020-04-06 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='months',
        ),
        migrations.RemoveField(
            model_name='course',
            name='year',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='months',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='year',
        ),
        migrations.RemoveField(
            model_name='extracurricular',
            name='months',
        ),
        migrations.RemoveField(
            model_name='extracurricular',
            name='year',
        ),
        migrations.AddField(
            model_name='course',
            name='date_ended',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='experience',
            name='current',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='experience',
            name='date_ended',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='experience',
            name='date_started',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='extracurricular',
            name='current',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='extracurricular',
            name='date_ended',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='extracurricular',
            name='date_started',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
