# Generated by Django 2.1.5 on 2020-04-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20200406_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='school',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
