# Generated by Django 2.1.5 on 2020-04-13 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_auto_20200411_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_ended',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='experience',
            name='date_ended',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='experience',
            name='date_started',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='extracurricular',
            name='date_ended',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='extracurricular',
            name='date_started',
            field=models.CharField(max_length=15),
        ),
    ]
